name: 'ForesightMiningSoftwareCorporation/rust-latest-version'
description: 'Github action to get the latest version of a crate from a registry index'
author: 'ForesightMiningSoftwareCorporation'
branding:
  icon: 'settings'
  color: 'green'
inputs:
  registry:
    required: true
    description: 'Path to a registry index (cloned on disk)'
  crate:
    required: true
    description: 'Name of the crate'
runs:
  using: 'node16'
  main: 'dist/index.js'
